version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: authdb
      POSTGRES_USER: authuser
      POSTGRES_PASSWORD: authpass
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  auth_system:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://authuser:authpass@db:5432/authdb
      SECRET_KEY: supersecretkey
    ports:
      - "8001:8001"
volumes:
  dbdata: