version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: whirly
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    env_file:
      - ./docker/.env.example
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app

  validator:
    build: ./backend
    command: ["python","-u","app/workers/validator.py"]
    env_file:
      - ./docker/.env.example
    depends_on:
      - backend
      - db
      - redis
    volumes:
      - ./backend/app:/app/app

  retrain:
    build: ./backend
    command: ["python","-u","app/workers/retrain_job.py"]
    env_file:
      - ./docker/.env.example
    depends_on:
      - validator
    volumes:
      - ./backend/app:/app/app

volumes:
  db_data: