name: CI
on: [push, pull_request]
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dev deps
        run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -q
  build-docker:
    runs-on: ubuntu-latest
    needs: lint-test
    steps:
      - uses: actions/checkout@v4
      - name: Build Docker Generator
        run: docker build -t whirly-synth-gen -f docker/Dockerfile.generator .
      - name: Push (optional)
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: user/whirly-synth-gen:latest